# Cognito user pool and one confidential app client (with a client secret) used by the
# BFF (USER_PASSWORD_AUTH). The secret is stored in an SSM SecureString parameter that
# only the BFF role can read. No hosted UI, no domain, no identity pool, no OAuth flows. Security invariants are
# fixed here; only the deletion protection comes from env.hcl.
#
# Accepted gap G1 (security design review): local users only, no federation, so the
# team rules COG-01 and COG-02 are reported by the audit and are not worked around.
#
# Secret in the Terraform state: the client secret generated by Cognito and the SSM
# parameter value are stored in clear text in the state file (a known limitation of the
# providers). The state bucket must stay encrypted with restricted access. The value is
# never an output and is never printed by Terraform (sensitive).
data "aws_region" "current" {}

locals {
  # Team naming convention: <acronym>-<region>-<context>[-<descriptor>]-<env-type>
  name_mid = "${replace(data.aws_region.current.region, "-", "")}-${var.context}"
}

resource "aws_cognito_user_pool" "this" {
  name = "cgnp-${local.name_mid}-${var.env_type}"

  # Cheapest tier. LITE covers every setting below (admin-only user creation, email as
  # username, password policy, MFA off, admin-only recovery, USER_PASSWORD_AUTH and
  # token revocation). Threat protection / advanced security is NOT used, and it is the
  # only feature here that would need a higher tier (Plus). Not confirmed against a
  # deployed pool: `plan` is pending the owner's approval.
  user_pool_tier = "LITE"

  deletion_protection = var.user_pool_deletion_protection

  # The email address is the username.
  username_attributes = ["email"]

  # Only administrators create users (no self sign-up).
  admin_create_user_config {
    allow_admin_create_user_only = true
  }

  password_policy {
    minimum_length                   = 12
    require_lowercase                = true
    require_uppercase                = true
    require_numbers                  = true
    require_symbols                  = true
    temporary_password_validity_days = 7
  }

  mfa_configuration = "OFF"

  # Account recovery by the administrator only.
  account_recovery_setting {
    recovery_mechanism {
      name     = "admin_only"
      priority = 1
    }
  }
}

resource "aws_cognito_user_pool_client" "this" {
  # Acronym "cgnc": Cognito user pool app client (naming-and-tagging.md).
  name         = "cgnc-${local.name_mid}-${var.env_type}"
  user_pool_id = aws_cognito_user_pool.this.id

  # Confidential client: Cognito generates a secret (stored in SSM below). Changing this
  # replaces the client (new client ID); nothing is deployed yet.
  generate_secret = true

  explicit_auth_flows = [
    "ALLOW_USER_PASSWORD_AUTH",
    "ALLOW_REFRESH_TOKEN_AUTH",
  ]

  # The refresh token is valid 24 hours from the login; rotation stays off (no
  # refresh_token_rotation block).
  refresh_token_validity = 24
  access_token_validity  = 1
  id_token_validity      = 1

  token_validity_units {
    refresh_token = "hours"
    access_token  = "hours"
    id_token      = "hours"
  }

  enable_token_revocation       = true
  prevent_user_existence_errors = "ENABLED"

  # No OAuth flows and no hosted UI: the app talks to Cognito only through the BFF.
  allowed_oauth_flows_user_pool_client = false
}

# Client secret for the BFF. SecureString with the AWS managed key (alias/aws/ssm, no
# CMK), standard tier. Name is a path: /<context>/<env-type>/auth/app-client-secret.
resource "aws_ssm_parameter" "app_client_secret" {
  name        = "/${var.context}/${var.env_type}/auth/app-client-secret"
  description = "Client secret of the Cognito app client used by the auth BFF"
  type        = "SecureString"
  tier        = "Standard"
  value       = aws_cognito_user_pool_client.this.client_secret
}
